#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

echo "BEGIN-SERVICE-------------------------------------------------------------------"

# This is just an example, you should build the binary using a multi-stage
# docker file for production

go mod tidy
go run .

echo "END-SERVICE---------------------------------------------------------------------"